Subindo Exercício01
marciogarridoLaCop/Estrutura-de-dados pull request #1
Opened 2023-08-22 15:08 UTC by YagoTarsin

2023-08-22 23:46 UTC, marciogarridoLaCop requested changes

2023-08-22 23:46 UTC, marciogarridoLaCop commented on README.md
Crie um novo arquivo com nome diferente do meu principal

2023-08-22 23:46 UTC, marciogarridoLaCop commented on exercicio_00.py
Não precisava ter apagado este aquivo.

2023-08-22 23:48 UTC, merged

2023-08-23 23:04 UTC, YagoTarsin commented
Entendido

On Tue, Aug 22, 2023 at 8:47 PM Marcio Garrido ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On README.md
> <https://github.com/marciogarridoLaCop/Estrutura-de-dados/pull/1#discussion_r1302302656>
> :
>
> Crie um novo arquivo com nome diferente do meu principal
> ------------------------------
>
> On exercicio_00.py
> <https://github.com/marciogarridoLaCop/Estrutura-de-dados/pull/1#discussion_r1302303504>
> :
>
> Não precisava ter apagado este aquivo.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/marciogarridoLaCop/Estrutura-de-dados/pull/1#pullrequestreview-1590502169>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYRJF27DJGK6ZS3SZXRTRSDXWVAHLANCNFSM6AAAAAA32CPMHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>